from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.historical_news.domain.enums import ContentStoragePolicy
from src.reaction_ready_corpus.domain import (
    SourceAuditEntry,
    SourceAuditStatus,
    source_audit_payload,
)


def audited_sources() -> tuple[SourceAuditEntry, ...]:
    return (
        SourceAuditEntry(
            tickers=("SBER", "SBERP"),
            issuer="Sberbank",
            source_url="https://www.sberbank.com/ru/investor-relations",
            source_owner="Sberbank",
            source_kind="OFFICIAL_IR_SITE",
            https=True,
            historical_depth_observed="Official IR pages observed; no stable public feed confirmed",
            timestamp_precision="Unverified for machine-readable feed",
            timezone_semantics="No verified machine-readable timestamp contract",
            full_text_availability="Official web pages only",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="No compliant feed/archive endpoint confirmed",
            robots_access_restrictions="No access controls were bypassed",
            status=SourceAuditStatus.NO_COMPLIANT_LIVE_SOURCE_AVAILABLE,
            blocker="No issuer-owned RSS, Atom, JSON API, or licensed local archive was available",
        ),
        SourceAuditEntry(
            tickers=("GAZP",),
            issuer="Gazprom",
            source_url="https://www.gazprom.com/press/news/",
            source_owner="Gazprom",
            source_kind="OFFICIAL_PRESS_ARCHIVE",
            https=True,
            historical_depth_observed="Multi-year official press archive",
            timestamp_precision="Exact timestamps visible on release pages",
            timezone_semantics="Page timestamps observed, but no feed contract verified",
            full_text_availability="Official release pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Archive exists; automated endpoint not confirmed",
            robots_access_restrictions="Direct controlled access timed out; no bypass attempted",
            status=SourceAuditStatus.SOURCE_ERROR,
            blocker="Official archive was not reliably reachable by the controlled client",
        ),
        SourceAuditEntry(
            tickers=("LKOH",),
            issuer="LUKOIL",
            source_url="https://www.lukoil.com/PressCenter/Pressreleases",
            source_owner="LUKOIL",
            source_kind="OFFICIAL_PRESS_ARCHIVE",
            https=True,
            historical_depth_observed="Official archive and RSS subscription advertised",
            timestamp_precision="Release pages observed; stable feed timestamps unverified",
            timezone_semantics="No stable public feed contract confirmed",
            full_text_availability="Official release pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability=(
                "Archive exists; RSS endpoint was not discoverable as stable URL"
            ),
            robots_access_restrictions="No undocumented endpoint or access control was used",
            status=SourceAuditStatus.NO_COMPLIANT_LIVE_SOURCE_AVAILABLE,
            blocker="Advertised RSS could not be resolved to a stable public endpoint",
        ),
        SourceAuditEntry(
            tickers=("ROSN",),
            issuer="Rosneft Oil Company",
            source_url="https://www.rosneft.com/press/releases/rss/",
            source_owner="Rosneft Oil Company",
            source_kind="ISSUER_RSS",
            https=True,
            historical_depth_observed="20 current official press releases in the RSS snapshot",
            timestamp_precision="Second precision with numeric UTC offset",
            timezone_semantics="RFC 822 pubDate includes +0300 offset; normalized to UTC",
            full_text_availability="Issuer-owned HTML excerpts in RSS descriptions",
            storage_policy=ContentStoragePolicy.EXCERPT_ALLOWED,
            pagination_archive_capability="Single bounded RSS page; no cursor or pagination",
            robots_access_restrictions="Public RSS advertised by issuer; robots.txt returned 404",
            status=SourceAuditStatus.COMPLIANT,
            source_code="ROSNEFT_PRESS_RELEASES_RSS",
        ),
        SourceAuditEntry(
            tickers=("NVTK",),
            issuer="NOVATEK",
            source_url="https://www.novatek.ru/en/press/releases/",
            source_owner="NOVATEK",
            source_kind="OFFICIAL_PRESS_ARCHIVE",
            https=True,
            historical_depth_observed="Deep official press archive",
            timestamp_precision="Date only in observed archive",
            timezone_semantics="No exact publication-time contract",
            full_text_availability="Official release pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Archive navigation available",
            robots_access_restrictions="No access controls were bypassed",
            status=SourceAuditStatus.TIMESTAMP_DATE_ONLY,
            blocker="Observed publication metadata does not provide an EXACT timestamp",
        ),
        SourceAuditEntry(
            tickers=("YDEX",),
            issuer="Yandex",
            source_url="https://ir.yandex/press-releases",
            source_owner="Yandex",
            source_kind="OFFICIAL_IR_ARCHIVE",
            https=True,
            historical_depth_observed="Official IR archive observed back to 2005",
            timestamp_precision="Date only in archive listing",
            timezone_semantics="No exact publication-time contract",
            full_text_availability="Official release pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Deep archive available",
            robots_access_restrictions="Controlled client could not establish reliable access",
            status=SourceAuditStatus.TIMESTAMP_DATE_ONLY,
            blocker="Observed metadata is DATE_ONLY and live access was unreliable",
        ),
        SourceAuditEntry(
            tickers=("T",),
            issuer="T-Technologies",
            source_url="https://www.tbank.ru/about/news/",
            source_owner="T-Technologies",
            source_kind="OFFICIAL_NEWS_ARCHIVE",
            https=True,
            historical_depth_observed="Official corporate news archive",
            timestamp_precision="Date only in observed listing",
            timezone_semantics="No exact publication-time contract",
            full_text_availability="Official news pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Archive listing available",
            robots_access_restrictions="No access controls were bypassed",
            status=SourceAuditStatus.TIMESTAMP_DATE_ONLY,
            blocker="Observed publication metadata does not provide an EXACT timestamp",
        ),
        SourceAuditEntry(
            tickers=("VTBR",),
            issuer="VTB Bank",
            source_url="https://www.vtb.com/ir/statements/results/",
            source_owner="VTB Bank",
            source_kind="OFFICIAL_IR_ARCHIVE",
            https=True,
            historical_depth_observed="Multi-year official results archive",
            timestamp_precision="Date only in observed archive",
            timezone_semantics="No exact publication-time contract",
            full_text_availability="Official releases and documents",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Archive by reporting period",
            robots_access_restrictions="No access controls were bypassed",
            status=SourceAuditStatus.TIMESTAMP_DATE_ONLY,
            blocker="Observed publication metadata does not provide an EXACT timestamp",
        ),
        SourceAuditEntry(
            tickers=("GMKN",),
            issuer="Nornickel",
            source_url="https://www.nornickel.com/investors/news-and-releases/",
            source_owner="Nornickel",
            source_kind="OFFICIAL_IR_ARCHIVE",
            https=True,
            historical_depth_observed="576 official investor news items observed",
            timestamp_precision="Date only in observed archive listing",
            timezone_semantics="No exact publication-time contract",
            full_text_availability="Official release pages",
            storage_policy=ContentStoragePolicy.UNKNOWN,
            pagination_archive_capability="Deep paginated archive",
            robots_access_restrictions="Public HTML accessible; no large-scale scraping attempted",
            status=SourceAuditStatus.TIMESTAMP_DATE_ONLY,
            blocker="Observed publication metadata does not provide an EXACT timestamp",
        ),
    )


def write_source_audit(path: Path) -> dict[str, Any]:
    payload = source_audit_payload(audited_sources())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return payload
