from __future__ import annotations

from src.free_historical_data.domain import (
    FreeSourceAudit,
    FreeSourceStatus,
    SourceVolume,
    VolumeEvidence,
)
from src.historical_news.domain.enums import ContentStoragePolicy, HistoricalNewsSourceKind
from src.news.domain.enums import PublicationTimestampQuality


def free_source_audits() -> tuple[FreeSourceAudit, ...]:
    audits = (
        _discovery(
            "SBER_IR_ARCHIVE",
            "Sberbank",
            ("SBER", "SBERP"),
            "Sberbank investor relations",
            "https://www.sberbank.com/ru/investor-relations",
            "Controlled requests timed out; no stable free machine-readable archive "
            "or exact-time contract was verified.",
            status=FreeSourceStatus.UNSTABLE,
        ),
        _discovery(
            "GAZPROM_PRESS_ARCHIVE",
            "Gazprom",
            ("GAZP",),
            "Gazprom news and events archive",
            "https://www.gazprom.com/press/news/",
            "Pages expose source clock times back to 2002, but direct controlled access "
            "timed out and automation policy could not be verified.",
            timestamp=PublicationTimestampQuality.EXACT,
            archive=True,
            pagination=True,
            estimated_items=5000,
            status=FreeSourceStatus.UNSTABLE,
        ),
        _discovery(
            "LUKOIL_PRESS_ARCHIVE",
            "PJSC LUKOIL",
            ("LKOH",),
            "LUKOIL press releases",
            "https://www.lukoil.com/PressCenter/Pressreleases",
            "A 248-page archive is public, but observed listings are date-only and "
            "automated-use terms were not verified.",
            timestamp=PublicationTimestampQuality.DATE_ONLY,
            archive=True,
            pagination=True,
            estimated_items=2480,
        ),
        FreeSourceAudit(
            source_code="ROSNEFT_PRESS_RELEASES_RSS",
            issuer="Rosneft Oil Company",
            tickers=("ROSN",),
            source_name="Rosneft official press-release RSS",
            source_url="https://www.rosneft.com/press/releases/rss/",
            source_kind=HistoricalNewsSourceKind.ISSUER_RSS,
            status=FreeSourceStatus.COMPLIANT_EXACT,
            issuer_owned=True,
            official=True,
            free=True,
            automation_allowed=True,
            robots_status="robots.txt returned 404; public RSS is explicitly published by issuer",
            terms_status="public feed; bounded polling only and no access controls",
            archive_available=False,
            pagination_available=False,
            sitemap_available=True,
            machine_readable=True,
            publication_datetime_available=True,
            timestamp_precision=PublicationTimestampQuality.EXACT,
            timezone_verified=True,
            earliest_verified_date="2025-06-20T15:30:00+03:00",
            latest_verified_date="2026-06-05T19:03:45+03:00",
            estimated_items=20,
            full_text_available=False,
            storage_policy=ContentStoragePolicy.EXCERPT_ALLOWED,
            stable_source_item_id="issuer-owned release URL",
            recommendation="bounded RSS backfill and incremental polling",
            blocking_reason=None,
        ),
        _discovery(
            "NOVATEK_PRESS_ARCHIVE",
            "PAO NOVATEK",
            ("NVTK",),
            "NOVATEK press releases",
            "https://www.novatek.ru/en/press/releases/",
            "Official multi-year archive exposes calendar dates without a proven "
            "publication clock time.",
            timestamp=PublicationTimestampQuality.DATE_ONLY,
            archive=True,
            pagination=True,
            estimated_items=500,
        ),
        FreeSourceAudit(
            source_code="YANDEX_IR_PRESS_RELEASES_RSS",
            issuer="Yandex",
            tickers=("YDEX",),
            source_name="Yandex official IR RSS",
            source_url="https://ir.yandex.ru/press-releases/news.rss",
            source_kind=HistoricalNewsSourceKind.ISSUER_RSS,
            status=FreeSourceStatus.COMPLIANT_EXACT,
            issuer_owned=True,
            official=True,
            free=True,
            automation_allowed=True,
            robots_status="public RSS linked by issuer IR site; bounded polling only",
            terms_status="public feed; no authentication, paywall, or private endpoint",
            archive_available=True,
            pagination_available=False,
            sitemap_available=False,
            machine_readable=True,
            publication_datetime_available=True,
            timestamp_precision=PublicationTimestampQuality.EXACT,
            timezone_verified=True,
            earliest_verified_date="2026-07-16T13:13:50+03:00",
            latest_verified_date="2026-08-11T11:00:00+03:00",
            estimated_items=20,
            full_text_available=False,
            storage_policy=ContentStoragePolicy.EXCERPT_ALLOWED,
            stable_source_item_id="issuer-owned GUID and release URL",
            recommendation="bounded RSS backfill and incremental polling",
            blocking_reason=None,
        ),
        _discovery(
            "YANDEX_IR_DATE_ARCHIVE",
            "Yandex",
            ("YDEX",),
            "Yandex IR yearly archive",
            "https://ir.yandex/press-releases",
            "Year pages reach 2005 but expose date-only metadata, so they are not "
            "historical EXACT evidence.",
            timestamp=PublicationTimestampQuality.DATE_ONLY,
            archive=True,
            pagination=True,
            estimated_items=600,
        ),
        _discovery(
            "T_BANK_NEWS_ARCHIVE",
            "T-Technologies",
            ("T",),
            "T-Bank corporate news",
            "https://www.tbank.ru/about/news/",
            "The JavaScript archive has no verified free machine-readable exact-time "
            "contract and controlled requests timed out.",
            status=FreeSourceStatus.UNSTABLE,
        ),
        _discovery(
            "VTB_IR_ARCHIVE",
            "VTB Bank",
            ("VTBR",),
            "VTB investor relations archive",
            "https://www.vtb.com/ir/statements/results/",
            "Controlled requests timed out and exact publication-time semantics were not verified.",
            archive=True,
            status=FreeSourceStatus.UNSTABLE,
        ),
        _discovery(
            "NORNICKEL_IR_ARCHIVE",
            "Nornickel",
            ("GMKN",),
            "Nornickel investor news and releases",
            "https://www.nornickel.com/investors/news-and-releases/",
            "A deep archive is visible, but observed metadata is date-only and "
            "automated-use terms remain unverified.",
            timestamp=PublicationTimestampQuality.DATE_ONLY,
            archive=True,
            pagination=True,
            estimated_items=576,
        ),
        _discovery(
            "MOEX_ISS_NEWS_RESEARCH",
            "Moscow Exchange",
            ("SBER", "SBERP", "GAZP", "LKOH", "ROSN", "NVTK", "YDEX", "T", "VTBR", "GMKN"),
            "MOEX ISS public API research",
            "https://iss.moex.com/iss/reference/",
            "Documented free delayed market data is not a verified issuer-news or "
            "disclosure corpus with publication timestamps.",
            machine=True,
        ),
        _paid(
            "MOEX_CORPORATE_INFORMATION",
            "Moscow Exchange / NSD",
            ("SBER", "SBERP", "GAZP", "LKOH", "ROSN", "NVTK", "YDEX", "T", "VTBR", "GMKN"),
            "MOEX corporate information product",
            "https://www.moex.com/a2836",
            "Corporate-information archives are subscription products and violate "
            "DATA_BUDGET=ZERO.",
        ),
        _paid(
            "INTERFAX_DISCLOSURE_API",
            "Interfax",
            ("SBER", "SBERP", "GAZP", "LKOH", "ROSN", "NVTK", "YDEX", "T", "VTBR", "GMKN"),
            "Interfax disclosure API/archive",
            "https://www.e-disclosure.ru/",
            "No verified free documented machine endpoint; paid access is permanently rejected.",
        ),
        _paid(
            "CBONDS_NEWS_API",
            "Cbonds",
            ("SBER", "SBERP", "GAZP", "LKOH", "ROSN", "NVTK", "YDEX", "T", "VTBR", "GMKN"),
            "Cbonds news/data API",
            "https://cbonds.ru/",
            "Commercial subscription/API is permanently rejected by DATA_BUDGET=ZERO.",
        ),
        _discovery(
            "OPEN_DATASET_RESEARCH",
            "Open-data ecosystem",
            ("SBER", "SBERP", "GAZP", "LKOH", "ROSN", "NVTK", "YDEX", "T", "VTBR", "GMKN"),
            "GitHub, Hugging Face, Kaggle, academic and government dataset audit",
            "https://huggingface.co/datasets",
            "No dataset was accepted because compatible license, real-news provenance, "
            "issuer mapping, and publication-time semantics were not jointly proven.",
        ),
    )
    for audit in audits:
        audit.validate()
    return audits


def source_volumes() -> tuple[SourceVolume, ...]:
    return (
        SourceVolume(
            source_code="ROSNEFT_PRESS_RELEASES_RSS",
            evidence=VolumeEvidence.VERIFIED,
            available_items=20,
            exact_items=20,
            date_only_items=0,
            date_from="2025-06-20T15:30:00+03:00",
            date_to="2026-06-05T19:03:45+03:00",
            issuers=("Rosneft Oil Company",),
            tickers=("ROSN",),
            eligible_for_acquisition=True,
            note="20 unique issuer RSS items already ingested; reruns are duplicates.",
        ),
        SourceVolume(
            source_code="YANDEX_IR_PRESS_RELEASES_RSS",
            evidence=VolumeEvidence.VERIFIED,
            available_items=20,
            exact_items=20,
            date_only_items=0,
            date_from="2026-07-16T13:13:50+03:00",
            date_to="2026-08-11T11:00:00+03:00",
            issuers=("Yandex",),
            tickers=("YDEX",),
            eligible_for_acquisition=True,
            note="20 unique issuer RSS items already ingested; reruns are duplicates.",
        ),
        SourceVolume(
            source_code="GAZPROM_PRESS_ARCHIVE",
            evidence=VolumeEvidence.ESTIMATED,
            available_items=5000,
            exact_items=5000,
            date_only_items=0,
            date_from="2002-01-01",
            date_to="2026-08-11",
            issuers=("Gazprom",),
            tickers=("GAZP",),
            eligible_for_acquisition=False,
            note=(
                "Archive depth and exact clock times are visible, but count, access "
                "stability, robots, and automation terms are not verified."
            ),
        ),
        SourceVolume(
            source_code="LUKOIL_PRESS_ARCHIVE",
            evidence=VolumeEvidence.ESTIMATED,
            available_items=2480,
            exact_items=0,
            date_only_items=2480,
            date_from="2001-01-01",
            date_to="2026-08-11",
            issuers=("PJSC LUKOIL",),
            tickers=("LKOH",),
            eligible_for_acquisition=False,
            note=(
                "248 ten-item pages are visible; item clock times and automation policy "
                "are unverified."
            ),
        ),
        SourceVolume(
            source_code="NORNICKEL_IR_ARCHIVE",
            evidence=VolumeEvidence.ESTIMATED,
            available_items=576,
            exact_items=0,
            date_only_items=576,
            date_from=None,
            date_to="2026-08-11",
            issuers=("Nornickel",),
            tickers=("GMKN",),
            eligible_for_acquisition=False,
            note=(
                "Prior bounded audit observed 576 date-only records; exact time and "
                "automation terms are not verified."
            ),
        ),
    )


def compliant_exact_audits() -> tuple[FreeSourceAudit, ...]:
    return tuple(
        audit for audit in free_source_audits() if audit.status == FreeSourceStatus.COMPLIANT_EXACT
    )


def _discovery(
    code: str,
    issuer: str,
    tickers: tuple[str, ...],
    name: str,
    url: str,
    blocker: str,
    *,
    timestamp: PublicationTimestampQuality = PublicationTimestampQuality.UNKNOWN,
    archive: bool = False,
    pagination: bool = False,
    machine: bool = False,
    estimated_items: int | None = None,
    status: FreeSourceStatus = FreeSourceStatus.DISCOVERY_ONLY,
) -> FreeSourceAudit:
    return FreeSourceAudit(
        source_code=code,
        issuer=issuer,
        tickers=tickers,
        source_name=name,
        source_url=url,
        source_kind=HistoricalNewsSourceKind.MANUAL_RESEARCH,
        status=status,
        issuer_owned=issuer not in {"Moscow Exchange", "Open-data ecosystem"},
        official=True,
        free=True,
        automation_allowed=False,
        robots_status="not proven for bounded archive automation",
        terms_status="not proven for bounded archive automation",
        archive_available=archive,
        pagination_available=pagination,
        sitemap_available=False,
        machine_readable=machine,
        publication_datetime_available=timestamp == PublicationTimestampQuality.EXACT,
        timestamp_precision=timestamp,
        timezone_verified=False,
        earliest_verified_date=None,
        latest_verified_date=None,
        estimated_items=estimated_items,
        full_text_available=False,
        storage_policy=ContentStoragePolicy.UNKNOWN,
        stable_source_item_id="issuer archive URL if later accepted",
        recommendation="research only; do not ingest until all acceptance fields are verified",
        blocking_reason=blocker,
    )


def _paid(
    code: str,
    issuer: str,
    tickers: tuple[str, ...],
    name: str,
    url: str,
    blocker: str,
) -> FreeSourceAudit:
    return FreeSourceAudit(
        source_code=code,
        issuer=issuer,
        tickers=tickers,
        source_name=name,
        source_url=url,
        source_kind=HistoricalNewsSourceKind.MANUAL_RESEARCH,
        status=FreeSourceStatus.REJECTED_PAID,
        issuer_owned=False,
        official=True,
        free=False,
        automation_allowed=False,
        robots_status="not applicable; source rejected before integration",
        terms_status="commercial access",
        archive_available=True,
        pagination_available=False,
        sitemap_available=False,
        machine_readable=True,
        publication_datetime_available=True,
        timestamp_precision=PublicationTimestampQuality.UNKNOWN,
        timezone_verified=False,
        earliest_verified_date=None,
        latest_verified_date=None,
        estimated_items=None,
        full_text_available=False,
        storage_policy=ContentStoragePolicy.UNKNOWN,
        stable_source_item_id="not evaluated because paid access is rejected",
        recommendation="REJECTED_PAID; never propose purchase as a blocker solution",
        blocking_reason=blocker,
    )
