from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    FINANCIAL_RESULTS = "FINANCIAL_RESULTS"
    DIVIDEND = "DIVIDEND"
    GUIDANCE = "GUIDANCE"
    MERGER_ACQUISITION = "MERGER_ACQUISITION"
    SHARE_ISSUANCE = "SHARE_ISSUANCE"
    BUYBACK = "BUYBACK"
    MANAGEMENT_CHANGE = "MANAGEMENT_CHANGE"
    MAJOR_CONTRACT = "MAJOR_CONTRACT"
    PRODUCTION_UPDATE = "PRODUCTION_UPDATE"
    REGULATORY_ACTION = "REGULATORY_ACTION"
    SANCTIONS = "SANCTIONS"
    LITIGATION = "LITIGATION"
    CREDIT_RATING = "CREDIT_RATING"
    DEBT_FINANCING = "DEBT_FINANCING"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class EventAnalysisStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_EVENT_FOUND = "NO_EVENT_FOUND"
    AMBIGUOUS = "AMBIGUOUS"
    FAILED = "FAILED"


class FinancialMetric(StrEnum):
    REVENUE = "REVENUE"
    NET_PROFIT = "NET_PROFIT"
    EBITDA = "EBITDA"
    OPERATING_PROFIT = "OPERATING_PROFIT"
    FREE_CASH_FLOW = "FREE_CASH_FLOW"
    CAPEX = "CAPEX"
    NET_DEBT = "NET_DEBT"
    DIVIDEND_PER_SHARE = "DIVIDEND_PER_SHARE"
    DIVIDEND_TOTAL = "DIVIDEND_TOTAL"
    PRODUCTION_VOLUME = "PRODUCTION_VOLUME"
    CONTRACT_VALUE = "CONTRACT_VALUE"
    OWNERSHIP_PERCENT = "OWNERSHIP_PERCENT"
    OTHER = "OTHER"


class FactUnit(StrEnum):
    MONEY = "MONEY"
    PERCENT = "PERCENT"
    PERCENTAGE_POINTS = "PERCENTAGE_POINTS"
    SHARES = "SHARES"
    TONNES = "TONNES"
    BARRELS = "BARRELS"
    CUBIC_METERS = "CUBIC_METERS"
    UNSPECIFIED = "UNSPECIFIED"


class Currency(StrEnum):
    RUB = "RUB"
    USD = "USD"
    EUR = "EUR"
    CNY = "CNY"
    UNSPECIFIED = "UNSPECIFIED"


class ValueScale(StrEnum):
    ONE = "ONE"
    THOUSAND = "THOUSAND"
    MILLION = "MILLION"
    BILLION = "BILLION"
    TRILLION = "TRILLION"


class FactRole(StrEnum):
    ACTUAL = "ACTUAL"
    PREVIOUS = "PREVIOUS"
    FORECAST = "FORECAST"
    CONSENSUS = "CONSENSUS"
    CHANGE = "CHANGE"
    TARGET = "TARGET"
    UNKNOWN = "UNKNOWN"


class ComparisonType(StrEnum):
    YEAR_OVER_YEAR = "YEAR_OVER_YEAR"
    QUARTER_OVER_QUARTER = "QUARTER_OVER_QUARTER"
    MONTH_OVER_MONTH = "MONTH_OVER_MONTH"
    VERSUS_FORECAST = "VERSUS_FORECAST"
    VERSUS_PREVIOUS = "VERSUS_PREVIOUS"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"


class PeriodType(StrEnum):
    YEAR = "YEAR"
    HALF_YEAR = "HALF_YEAR"
    QUARTER = "QUARTER"
    NINE_MONTHS = "NINE_MONTHS"
    MONTH = "MONTH"
    DATE_RANGE = "DATE_RANGE"
    UNKNOWN = "UNKNOWN"


class ChangeDirection(StrEnum):
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"
